using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CorpusExplorer.Sdk.Extern.TileGridMap
{
  public static class StaticCountryData
  {
    public static GridTileMap[] Data = new[]
    {
      new GridTileMap
      {
        Name = "Afghanistan",
        Alpha2 = "AF",
        Alpha3 = "AFG",
        Coordinates = new[] {22, 8},
        CountryCode = "004",
        Iso31662 = "ISO 3166-2:AF",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Southern Asia",
        SubRegionCode = "034",
      },
      new GridTileMap
      {
        Name = "Albania",
        Alpha2 = "AL",
        Alpha3 = "ALB",
        Coordinates = new[] {15, 9},
        CountryCode = "008",
        Iso31662 = "ISO 3166-2:AL",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Southern Europe",
        SubRegionCode = "039",
      },
      new GridTileMap
      {
        Name = "Algeria",
        Alpha2 = "DZ",
        Alpha3 = "DZA",
        Coordinates = new[] {13, 11},
        CountryCode = "012",
        Iso31662 = "ISO 3166-2:DZ",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Northern Africa",
        SubRegionCode = "015",
      },
      new GridTileMap
      {
        Name = "Angola",
        Alpha2 = "AO",
        Alpha3 = "AGO",
        Coordinates = new[] {13, 17},
        CountryCode = "024",
        Iso31662 = "ISO 3166-2:AO",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Middle Africa",
        SubRegionCode = "017",
      },
      new GridTileMap
      {
        Name = "Antarctica",
        Alpha2 = "AQ",
        Alpha3 = "ATA",
        Coordinates = new[] {15, 23},
        CountryCode = "010",
        Iso31662 = "ISO 3166-2:AQ",
        Region = "",
        RegionCode = "",
        SubRegion = "",
        SubRegionCode = "",
      },
      new GridTileMap
      {
        Name = "Antigua & Barbuda",
        Alpha2 = "AG",
        Alpha3 = "ATG",
        Coordinates = new[] {7, 4},
        CountryCode = "028",
        Iso31662 = "ISO 3166-2:AG",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Caribbean",
        SubRegionCode = "029",
      },
      new GridTileMap
      {
        Name = "Argentina",
        Alpha2 = "AR",
        Alpha3 = "ARG",
        Coordinates = new[] {6, 14},
        CountryCode = "032",
        Iso31662 = "ISO 3166-2:AR",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "South America",
        SubRegionCode = "005",
      },
      new GridTileMap
      {
        Name = "Armenia",
        Alpha2 = "AM",
        Alpha3 = "ARM",
        Coordinates = new[] {20, 6},
        CountryCode = "051",
        Iso31662 = "ISO 3166-2:AM",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Western Asia",
        SubRegionCode = "145",
      },
      new GridTileMap
      {
        Name = "Australia",
        Alpha2 = "AU",
        Alpha3 = "AUS",
        Coordinates = new[] {24, 19},
        CountryCode = "036",
        Iso31662 = "ISO 3166-2:AU",
        Region = "Oceania",
        RegionCode = "009",
        SubRegion = "Australia and New Zealand",
        SubRegionCode = "053",
      },
      new GridTileMap
      {
        Name = "Austria",
        Alpha2 = "AT",
        Alpha3 = "AUT",
        Coordinates = new[] {15, 6},
        CountryCode = "040",
        Iso31662 = "ISO 3166-2:AT",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Western Europe",
        SubRegionCode = "155",
      },
      new GridTileMap
      {
        Name = "Azerbaijan",
        Alpha2 = "AZ",
        Alpha3 = "AZE",
        Coordinates = new[] {21, 7},
        CountryCode = "031",
        Iso31662 = "ISO 3166-2:AZ",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Western Asia",
        SubRegionCode = "145",
      },
      new GridTileMap
      {
        Name = "Bahamas",
        Alpha2 = "BS",
        Alpha3 = "BHS",
        Coordinates = new[] {4, 2},
        CountryCode = "044",
        Iso31662 = "ISO 3166-2:BS",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Caribbean",
        SubRegionCode = "029",
      },
      new GridTileMap
      {
        Name = "Bahrain",
        Alpha2 = "BH",
        Alpha3 = "BHR",
        Coordinates = new[] {20, 9},
        CountryCode = "048",
        Iso31662 = "ISO 3166-2:BH",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Western Asia",
        SubRegionCode = "145",
      },
      new GridTileMap
      {
        Name = "Bangladesh",
        Alpha2 = "BD",
        Alpha3 = "BGD",
        Coordinates = new[] {23, 8},
        CountryCode = "050",
        Iso31662 = "ISO 3166-2:BD",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Southern Asia",
        SubRegionCode = "034",
      },
      new GridTileMap
      {
        Name = "Barbados",
        Alpha2 = "BB",
        Alpha3 = "BRB",
        Coordinates = new[] {8, 6},
        CountryCode = "052",
        Iso31662 = "ISO 3166-2:BB",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Caribbean",
        SubRegionCode = "029",
      },
      new GridTileMap
      {
        Name = "Belarus",
        Alpha2 = "BY",
        Alpha3 = "BLR",
        Coordinates = new[] {17, 4},
        CountryCode = "112",
        Iso31662 = "ISO 3166-2:BY",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Eastern Europe",
        SubRegionCode = "151",
      },
      new GridTileMap
      {
        Name = "Belgium",
        Alpha2 = "BE",
        Alpha3 = "BEL",
        Coordinates = new[] {13, 5},
        CountryCode = "056",
        Iso31662 = "ISO 3166-2:BE",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Western Europe",
        SubRegionCode = "155",
      },
      new GridTileMap
      {
        Name = "Belize",
        Alpha2 = "BZ",
        Alpha3 = "BLZ",
        Coordinates = new[] {2, 3},
        CountryCode = "084",
        Iso31662 = "ISO 3166-2:BZ",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Central America",
        SubRegionCode = "013",
      },
      new GridTileMap
      {
        Name = "Benin",
        Alpha2 = "BJ",
        Alpha3 = "BEN",
        Coordinates = new[] {15, 14},
        CountryCode = "204",
        Iso31662 = "ISO 3166-2:BJ",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Western Africa",
        SubRegionCode = "011",
      },
      new GridTileMap
      {
        Name = "Bhutan",
        Alpha2 = "BT",
        Alpha3 = "BTN",
        Coordinates = new[] {24, 7},
        CountryCode = "064",
        Iso31662 = "ISO 3166-2:BT",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Southern Asia",
        SubRegionCode = "034",
      },
      new GridTileMap
      {
        Name = "Bolivia",
        Alpha2 = "BO",
        Alpha3 = "BOL",
        Coordinates = new[] {6, 11},
        CountryCode = "068",
        Iso31662 = "ISO 3166-2:BO",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "South America",
        SubRegionCode = "005",
      },
      new GridTileMap
      {
        Name = "Bosnia & Herzegovina",
        Alpha2 = "BA",
        Alpha3 = "BIH",
        Coordinates = new[] {15, 7},
        CountryCode = "070",
        Iso31662 = "ISO 3166-2:BA",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Southern Europe",
        SubRegionCode = "039",
      },
      new GridTileMap
      {
        Name = "Botswana",
        Alpha2 = "BW",
        Alpha3 = "BWA",
        Coordinates = new[] {15, 18},
        CountryCode = "072",
        Iso31662 = "ISO 3166-2:BW",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Southern Africa",
        SubRegionCode = "018",
      },
      new GridTileMap
      {
        Name = "Brazil",
        Alpha2 = "BR",
        Alpha3 = "BRA",
        Coordinates = new[] {8, 11},
        CountryCode = "076",
        Iso31662 = "ISO 3166-2:BR",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "South America",
        SubRegionCode = "005",
      },
      new GridTileMap
      {
        Name = "Brunei Darussalam",
        Alpha2 = "BN",
        Alpha3 = "BRN",
        Coordinates = new[] {25, 12},
        CountryCode = "096",
        Iso31662 = "ISO 3166-2:BN",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "South-Eastern Asia",
        SubRegionCode = "035",
      },
      new GridTileMap
      {
        Name = "Bulgaria",
        Alpha2 = "BG",
        Alpha3 = "BGR",
        Coordinates = new[] {17, 7},
        CountryCode = "100",
        Iso31662 = "ISO 3166-2:BG",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Eastern Europe",
        SubRegionCode = "151",
      },
      new GridTileMap
      {
        Name = "Burkina Faso",
        Alpha2 = "BF",
        Alpha3 = "BFA",
        Coordinates = new[] {13, 13},
        CountryCode = "854",
        Iso31662 = "ISO 3166-2:BF",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Western Africa",
        SubRegionCode = "011",
      },
      new GridTileMap
      {
        Name = "Burundi",
        Alpha2 = "BI",
        Alpha3 = "BDI",
        Coordinates = new[] {15, 16},
        CountryCode = "108",
        Iso31662 = "ISO 3166-2:BI",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Eastern Africa",
        SubRegionCode = "014",
      },
      new GridTileMap
      {
        Name = "Cambodia",
        Alpha2 = "KH",
        Alpha3 = "KHM",
        Coordinates = new[] {25, 10},
        CountryCode = "116",
        Iso31662 = "ISO 3166-2:KH",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "South-Eastern Asia",
        SubRegionCode = "035",
      },
      new GridTileMap
      {
        Name = "Cameroon",
        Alpha2 = "CM",
        Alpha3 = "CMR",
        Coordinates = new[] {14, 15},
        CountryCode = "120",
        Iso31662 = "ISO 3166-2:CM",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Middle Africa",
        SubRegionCode = "017",
      },
      new GridTileMap
      {
        Name = "Canada",
        Alpha2 = "CA",
        Alpha3 = "CAN",
        Coordinates = new[] {1, 1},
        CountryCode = "124",
        Iso31662 = "ISO 3166-2:CA",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Northern America",
        SubRegionCode = "021",
      },
      new GridTileMap
      {
        Name = "Cabo Verde",
        Alpha2 = "CV",
        Alpha3 = "CPV",
        Coordinates = new[] {10, 15},
        CountryCode = "132",
        Iso31662 = "ISO 3166-2:CV",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Western Africa",
        SubRegionCode = "011",
      },
      new GridTileMap
      {
        Name = "Central African Republic",
        Alpha2 = "CF",
        Alpha3 = "CAF",
        Coordinates = new[] {16, 14},
        CountryCode = "140",
        Iso31662 = "ISO 3166-2:CF",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Middle Africa",
        SubRegionCode = "017",
      },
      new GridTileMap
      {
        Name = "Chad",
        Alpha2 = "TD",
        Alpha3 = "TCD",
        Coordinates = new[] {14, 13},
        CountryCode = "148",
        Iso31662 = "ISO 3166-2:TD",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Middle Africa",
        SubRegionCode = "017",
      },
      new GridTileMap
      {
        Name = "Chile",
        Alpha2 = "CL",
        Alpha3 = "CHL",
        Coordinates = new[] {6, 13},
        CountryCode = "152",
        Iso31662 = "ISO 3166-2:CL",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "South America",
        SubRegionCode = "005",
      },
      new GridTileMap
      {
        Name = "China",
        Alpha2 = "CN",
        Alpha3 = "CHN",
        Coordinates = new[] {24, 6},
        CountryCode = "156",
        Iso31662 = "ISO 3166-2:CN",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Eastern Asia",
        SubRegionCode = "030",
      },
      new GridTileMap
      {
        Name = "Colombia",
        Alpha2 = "CO",
        Alpha3 = "COL",
        Coordinates = new[] {5, 9},
        CountryCode = "170",
        Iso31662 = "ISO 3166-2:CO",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "South America",
        SubRegionCode = "005",
      },
      new GridTileMap
      {
        Name = "Comoros",
        Alpha2 = "KM",
        Alpha3 = "COM",
        Coordinates = new[] {18, 18},
        CountryCode = "174",
        Iso31662 = "ISO 3166-2:KM",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Eastern Africa",
        SubRegionCode = "014",
      },
      new GridTileMap
      {
        Name = "Congo",
        Alpha2 = "CG",
        Alpha3 = "COG",
        Coordinates = new[] {14, 16},
        CountryCode = "178",
        Iso31662 = "ISO 3166-2:CG",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Middle Africa",
        SubRegionCode = "017",
      },
      new GridTileMap
      {
        Name = "Congo (Democratic Republic of the)",
        Alpha2 = "CD",
        Alpha3 = "COD",
        Coordinates = new[] {15, 15},
        CountryCode = "180",
        Iso31662 = "ISO 3166-2:CD",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Middle Africa",
        SubRegionCode = "017",
      },
      new GridTileMap
      {
        Name = "Costa Rica",
        Alpha2 = "CR",
        Alpha3 = "CRI",
        Coordinates = new[] {3, 7},
        CountryCode = "188",
        Iso31662 = "ISO 3166-2:CR",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Central America",
        SubRegionCode = "013",
      },
      new GridTileMap
      {
        Name = "Côte d'Ivoire",
        Alpha2 = "CI",
        Alpha3 = "CIV",
        Coordinates = new[] {12, 15},
        CountryCode = "384",
        Iso31662 = "ISO 3166-2:CI",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Western Africa",
        SubRegionCode = "011",
      },
      new GridTileMap
      {
        Name = "Croatia",
        Alpha2 = "HR",
        Alpha3 = "HRV",
        Coordinates = new[] {14, 7},
        CountryCode = "191",
        Iso31662 = "ISO 3166-2:HR",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Southern Europe",
        SubRegionCode = "039",
      },
      new GridTileMap
      {
        Name = "Cuba",
        Alpha2 = "CU",
        Alpha3 = "CUB",
        Coordinates = new[] {4, 3},
        CountryCode = "192",
        Iso31662 = "ISO 3166-2:CU",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Caribbean",
        SubRegionCode = "029",
      },
      new GridTileMap
      {
        Name = "Cyprus",
        Alpha2 = "CY",
        Alpha3 = "CYP",
        Coordinates = new[] {17, 10},
        CountryCode = "196",
        Iso31662 = "ISO 3166-2:CY",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Western Asia",
        SubRegionCode = "145",
      },
      new GridTileMap
      {
        Name = "Czech Republic",
        Alpha2 = "CZ",
        Alpha3 = "CZE",
        Coordinates = new[] {15, 5},
        CountryCode = "203",
        Iso31662 = "ISO 3166-2:CZ",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Eastern Europe",
        SubRegionCode = "151",
      },
      new GridTileMap
      {
        Name = "Denmark",
        Alpha2 = "DK",
        Alpha3 = "DNK",
        Coordinates = new[] {14, 3},
        CountryCode = "208",
        Iso31662 = "ISO 3166-2:DK",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Northern Europe",
        SubRegionCode = "154",
      },
      new GridTileMap
      {
        Name = "Djibouti",
        Alpha2 = "DJ",
        Alpha3 = "DJI",
        Coordinates = new[] {17, 13},
        CountryCode = "262",
        Iso31662 = "ISO 3166-2:DJ",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Eastern Africa",
        SubRegionCode = "014",
      },
      new GridTileMap
      {
        Name = "Dominica",
        Alpha2 = "DM",
        Alpha3 = "DMA",
        Coordinates = new[] {7, 7},
        CountryCode = "212",
        Iso31662 = "ISO 3166-2:DM",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Caribbean",
        SubRegionCode = "029",
      },
      new GridTileMap
      {
        Name = "Dominican Republic",
        Alpha2 = "DO",
        Alpha3 = "DOM",
        Coordinates = new[] {6, 4},
        CountryCode = "214",
        Iso31662 = "ISO 3166-2:DO",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Caribbean",
        SubRegionCode = "029",
      },
      new GridTileMap
      {
        Name = "Ecuador",
        Alpha2 = "EC",
        Alpha3 = "ECU",
        Coordinates = new[] {5, 10},
        CountryCode = "218",
        Iso31662 = "ISO 3166-2:EC",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "South America",
        SubRegionCode = "005",
      },
      new GridTileMap
      {
        Name = "Egypt",
        Alpha2 = "EG",
        Alpha3 = "EGY",
        Coordinates = new[] {16, 11},
        CountryCode = "818",
        Iso31662 = "ISO 3166-2:EG",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Northern Africa",
        SubRegionCode = "015",
      },
      new GridTileMap
      {
        Name = "El Salvador",
        Alpha2 = "SV",
        Alpha3 = "SLV",
        Coordinates = new[] {1, 5},
        CountryCode = "222",
        Iso31662 = "ISO 3166-2:SV",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Central America",
        SubRegionCode = "013",
      },
      new GridTileMap
      {
        Name = "Equatorial Guinea",
        Alpha2 = "GQ",
        Alpha3 = "GNQ",
        Coordinates = new[] {13, 16},
        CountryCode = "226",
        Iso31662 = "ISO 3166-2:GQ",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Middle Africa",
        SubRegionCode = "017",
      },
      new GridTileMap
      {
        Name = "Eritrea",
        Alpha2 = "ER",
        Alpha3 = "ERI",
        Coordinates = new[] {16, 13},
        CountryCode = "232",
        Iso31662 = "ISO 3166-2:ER",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Eastern Africa",
        SubRegionCode = "014",
      },
      new GridTileMap
      {
        Name = "Estonia",
        Alpha2 = "EE",
        Alpha3 = "EST",
        Coordinates = new[] {17, 2},
        CountryCode = "233",
        Iso31662 = "ISO 3166-2:EE",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Northern Europe",
        SubRegionCode = "154",
      },
      new GridTileMap
      {
        Name = "Ethiopia",
        Alpha2 = "ET",
        Alpha3 = "ETH",
        Coordinates = new[] {17, 14},
        CountryCode = "231",
        Iso31662 = "ISO 3166-2:ET",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Eastern Africa",
        SubRegionCode = "014",
      },
      new GridTileMap
      {
        Name = "Fiji",
        Alpha2 = "FJ",
        Alpha3 = "FJI",
        Coordinates = new[] {27, 19},
        CountryCode = "242",
        Iso31662 = "ISO 3166-2:FJ",
        Region = "Oceania",
        RegionCode = "009",
        SubRegion = "Melanesia",
        SubRegionCode = "054",
      },
      new GridTileMap
      {
        Name = "Finland",
        Alpha2 = "FI",
        Alpha3 = "FIN",
        Coordinates = new[] {17, 1},
        CountryCode = "246",
        Iso31662 = "ISO 3166-2:FI",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Northern Europe",
        SubRegionCode = "154",
      },
      new GridTileMap
      {
        Name = "France",
        Alpha2 = "FR",
        Alpha3 = "FRA",
        Coordinates = new[] {12, 5},
        CountryCode = "250",
        Iso31662 = "ISO 3166-2:FR",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Western Europe",
        SubRegionCode = "155",
      },
      new GridTileMap
      {
        Name = "Gabon",
        Alpha2 = "GA",
        Alpha3 = "GAB",
        Coordinates = new[] {14, 17},
        CountryCode = "266",
        Iso31662 = "ISO 3166-2:GA",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Middle Africa",
        SubRegionCode = "017",
      },
      new GridTileMap
      {
        Name = "Gambia",
        Alpha2 = "GM",
        Alpha3 = "GMB",
        Coordinates = new[] {12, 12},
        CountryCode = "270",
        Iso31662 = "ISO 3166-2:GM",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Western Africa",
        SubRegionCode = "011",
      },
      new GridTileMap
      {
        Name = "Georgia",
        Alpha2 = "GE",
        Alpha3 = "GEO",
        Coordinates = new[] {21, 6},
        CountryCode = "268",
        Iso31662 = "ISO 3166-2:GE",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Western Asia",
        SubRegionCode = "145",
      },
      new GridTileMap
      {
        Name = "Germany",
        Alpha2 = "DE",
        Alpha3 = "DEU",
        Coordinates = new[] {14, 4},
        CountryCode = "276",
        Iso31662 = "ISO 3166-2:DE",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Western Europe",
        SubRegionCode = "155",
      },
      new GridTileMap
      {
        Name = "Ghana",
        Alpha2 = "GH",
        Alpha3 = "GHA",
        Coordinates = new[] {13, 14},
        CountryCode = "288",
        Iso31662 = "ISO 3166-2:GH",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Western Africa",
        SubRegionCode = "011",
      },
      new GridTileMap
      {
        Name = "Greece",
        Alpha2 = "GR",
        Alpha3 = "GRC",
        Coordinates = new[] {16, 9},
        CountryCode = "300",
        Iso31662 = "ISO 3166-2:GR",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Southern Europe",
        SubRegionCode = "039",
      },
      new GridTileMap
      {
        Name = "Greenland",
        Alpha2 = "GL",
        Alpha3 = "GRL",
        Coordinates = new[] {8, 1},
        CountryCode = "304",
        Iso31662 = "ISO 3166-2:GL",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Northern America",
        SubRegionCode = "021",
      },
      new GridTileMap
      {
        Name = "Grenada",
        Alpha2 = "GD",
        Alpha3 = "GRD",
        Coordinates = new[] {7, 8},
        CountryCode = "308",
        Iso31662 = "ISO 3166-2:GD",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Caribbean",
        SubRegionCode = "029",
      },
      new GridTileMap
      {
        Name = "Guatemala",
        Alpha2 = "GT",
        Alpha3 = "GTM",
        Coordinates = new[] {1, 4},
        CountryCode = "320",
        Iso31662 = "ISO 3166-2:GT",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Central America",
        SubRegionCode = "013",
      },
      new GridTileMap
      {
        Name = "Guinea",
        Alpha2 = "GN",
        Alpha3 = "GIN",
        Coordinates = new[] {11, 14},
        CountryCode = "324",
        Iso31662 = "ISO 3166-2:GN",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Western Africa",
        SubRegionCode = "011",
      },
      new GridTileMap
      {
        Name = "Guinea-Bissau",
        Alpha2 = "GW",
        Alpha3 = "GNB",
        Coordinates = new[] {11, 13},
        CountryCode = "624",
        Iso31662 = "ISO 3166-2:GW",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Western Africa",
        SubRegionCode = "011",
      },
      new GridTileMap
      {
        Name = "Guyana",
        Alpha2 = "GY",
        Alpha3 = "GUY",
        Coordinates = new[] {6, 10},
        CountryCode = "328",
        Iso31662 = "ISO 3166-2:GY",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "South America",
        SubRegionCode = "005",
      },
      new GridTileMap
      {
        Name = "Haiti",
        Alpha2 = "HT",
        Alpha3 = "HTI",
        Coordinates = new[] {5, 4},
        CountryCode = "332",
        Iso31662 = "ISO 3166-2:HT",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Caribbean",
        SubRegionCode = "029",
      },
      new GridTileMap
      {
        Name = "Honduras",
        Alpha2 = "HN",
        Alpha3 = "HND",
        Coordinates = new[] {2, 5},
        CountryCode = "340",
        Iso31662 = "ISO 3166-2:HN",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Central America",
        SubRegionCode = "013",
      },
      new GridTileMap
      {
        Name = "Hungary",
        Alpha2 = "HU",
        Alpha3 = "HUN",
        Coordinates = new[] {16, 6},
        CountryCode = "348",
        Iso31662 = "ISO 3166-2:HU",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Eastern Europe",
        SubRegionCode = "151",
      },
      new GridTileMap
      {
        Name = "Iceland",
        Alpha2 = "IS",
        Alpha3 = "ISL",
        Coordinates = new[] {10, 1},
        CountryCode = "352",
        Iso31662 = "ISO 3166-2:IS",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Northern Europe",
        SubRegionCode = "154",
      },
      new GridTileMap
      {
        Name = "India",
        Alpha2 = "IN",
        Alpha3 = "IND",
        Coordinates = new[] {22, 9},
        CountryCode = "356",
        Iso31662 = "ISO 3166-2:IN",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Southern Asia",
        SubRegionCode = "034",
      },
      new GridTileMap
      {
        Name = "Indonesia",
        Alpha2 = "ID",
        Alpha3 = "IDN",
        Coordinates = new[] {25, 13},
        CountryCode = "360",
        Iso31662 = "ISO 3166-2:ID",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "South-Eastern Asia",
        SubRegionCode = "035",
      },
      new GridTileMap
      {
        Name = "Iran (Islamic Republic of)",
        Alpha2 = "IR",
        Alpha3 = "IRN",
        Coordinates = new[] {20, 8},
        CountryCode = "364",
        Iso31662 = "ISO 3166-2:IR",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Southern Asia",
        SubRegionCode = "034",
      },
      new GridTileMap
      {
        Name = "Iraq",
        Alpha2 = "IQ",
        Alpha3 = "IRQ",
        Coordinates = new[] {20, 7},
        CountryCode = "368",
        Iso31662 = "ISO 3166-2:IQ",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Western Asia",
        SubRegionCode = "145",
      },
      new GridTileMap
      {
        Name = "Ireland",
        Alpha2 = "IE",
        Alpha3 = "IRL",
        Coordinates = new[] {10, 4},
        CountryCode = "372",
        Iso31662 = "ISO 3166-2:IE",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Northern Europe",
        SubRegionCode = "154",
      },
      new GridTileMap
      {
        Name = "Israel",
        Alpha2 = "IL",
        Alpha3 = "ISR",
        Coordinates = new[] {18, 10},
        CountryCode = "376",
        Iso31662 = "ISO 3166-2:IL",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Western Asia",
        SubRegionCode = "145",
      },
      new GridTileMap
      {
        Name = "Italy",
        Alpha2 = "IT",
        Alpha3 = "ITA",
        Coordinates = new[] {13, 7},
        CountryCode = "380",
        Iso31662 = "ISO 3166-2:IT",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Southern Europe",
        SubRegionCode = "039",
      },
      new GridTileMap
      {
        Name = "Jamaica",
        Alpha2 = "JM",
        Alpha3 = "JAM",
        Coordinates = new[] {4, 4},
        CountryCode = "388",
        Iso31662 = "ISO 3166-2:JM",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Caribbean",
        SubRegionCode = "029",
      },
      new GridTileMap
      {
        Name = "Japan",
        Alpha2 = "JP",
        Alpha3 = "JPN",
        Coordinates = new[] {27, 6},
        CountryCode = "392",
        Iso31662 = "ISO 3166-2:JP",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Eastern Asia",
        SubRegionCode = "030",
      },
      new GridTileMap
      {
        Name = "Jordan",
        Alpha2 = "JO",
        Alpha3 = "JOR",
        Coordinates = new[] {18, 8},
        CountryCode = "400",
        Iso31662 = "ISO 3166-2:JO",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Western Asia",
        SubRegionCode = "145",
      },
      new GridTileMap
      {
        Name = "Kazakhstan",
        Alpha2 = "KZ",
        Alpha3 = "KAZ",
        Coordinates = new[] {24, 5},
        CountryCode = "398",
        Iso31662 = "ISO 3166-2:KZ",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Central Asia",
        SubRegionCode = "143",
      },
      new GridTileMap
      {
        Name = "Kenya",
        Alpha2 = "KE",
        Alpha3 = "KEN",
        Coordinates = new[] {17, 15},
        CountryCode = "404",
        Iso31662 = "ISO 3166-2:KE",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Eastern Africa",
        SubRegionCode = "014",
      },
      new GridTileMap
      {
        Name = "Kiribati",
        Alpha2 = "KI",
        Alpha3 = "KIR",
        Coordinates = new[] {27, 17},
        CountryCode = "296",
        Iso31662 = "ISO 3166-2:KI",
        Region = "Oceania",
        RegionCode = "009",
        SubRegion = "Micronesia",
        SubRegionCode = "057",
      },
      new GridTileMap
      {
        Name = "North Korea",
        Alpha2 = "KP",
        Alpha3 = "PRK",
        Coordinates = new[] {25, 6},
        CountryCode = "408",
        Iso31662 = "ISO 3166-2:KP",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Eastern Asia",
        SubRegionCode = "030",
      },
      new GridTileMap
      {
        Name = "South Korea",
        Alpha2 = "KR",
        Alpha3 = "KOR",
        Coordinates = new[] {25, 7},
        CountryCode = "410",
        Iso31662 = "ISO 3166-2:KR",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Eastern Asia",
        SubRegionCode = "030",
      },
      new GridTileMap
      {
        Name = "Kosovo",
        Alpha2 = "XK",
        Alpha3 = "XKX",
        Coordinates = new[] {16, 8},
        CountryCode = "383",
        Iso31662 = "ISO 3166-2:XK",
        Region = "Europe",
        RegionCode = "142",
        SubRegion = "Southern Europe",
        SubRegionCode = "030",
      },
      new GridTileMap
      {
        Name = "Kuwait",
        Alpha2 = "KW",
        Alpha3 = "KWT",
        Coordinates = new[] {19, 8},
        CountryCode = "414",
        Iso31662 = "ISO 3166-2:KW",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Western Asia",
        SubRegionCode = "145",
      },
      new GridTileMap
      {
        Name = "Kyrgyzstan",
        Alpha2 = "KG",
        Alpha3 = "KGZ",
        Coordinates = new[] {23, 6},
        CountryCode = "417",
        Iso31662 = "ISO 3166-2:KG",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Central Asia",
        SubRegionCode = "143",
      },
      new GridTileMap
      {
        Name = "Lao People's Democratic Republic",
        Alpha2 = "LA",
        Alpha3 = "LAO",
        Coordinates = new[] {25, 9},
        CountryCode = "418",
        Iso31662 = "ISO 3166-2:LA",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "South-Eastern Asia",
        SubRegionCode = "035",
      },
      new GridTileMap
      {
        Name = "Latvia",
        Alpha2 = "LV",
        Alpha3 = "LVA",
        Coordinates = new[] {17, 3},
        CountryCode = "428",
        Iso31662 = "ISO 3166-2:LV",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Northern Europe",
        SubRegionCode = "154",
      },
      new GridTileMap
      {
        Name = "Lebanon",
        Alpha2 = "LB",
        Alpha3 = "LBN",
        Coordinates = new[] {18, 9},
        CountryCode = "422",
        Iso31662 = "ISO 3166-2:LB",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Western Asia",
        SubRegionCode = "145",
      },
      new GridTileMap
      {
        Name = "Lesotho",
        Alpha2 = "LS",
        Alpha3 = "LSO",
        Coordinates = new[] {17, 19},
        CountryCode = "426",
        Iso31662 = "ISO 3166-2:LS",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Southern Africa",
        SubRegionCode = "018",
      },
      new GridTileMap
      {
        Name = "Liberia",
        Alpha2 = "LR",
        Alpha3 = "LBR",
        Coordinates = new[] {12, 14},
        CountryCode = "430",
        Iso31662 = "ISO 3166-2:LR",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Western Africa",
        SubRegionCode = "011",
      },
      new GridTileMap
      {
        Name = "Libya",
        Alpha2 = "LY",
        Alpha3 = "LBY",
        Coordinates = new[] {15, 11},
        CountryCode = "434",
        Iso31662 = "ISO 3166-2:LY",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Northern Africa",
        SubRegionCode = "015",
      },
      new GridTileMap
      {
        Name = "Lithuania",
        Alpha2 = "LT",
        Alpha3 = "LTU",
        Coordinates = new[] {16, 4},
        CountryCode = "440",
        Iso31662 = "ISO 3166-2:LT",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Northern Europe",
        SubRegionCode = "154",
      },
      new GridTileMap
      {
        Name = "Luxembourg",
        Alpha2 = "LU",
        Alpha3 = "LUX",
        Coordinates = new[] {13, 6},
        CountryCode = "442",
        Iso31662 = "ISO 3166-2:LU",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Western Europe",
        SubRegionCode = "155",
      },
      new GridTileMap
      {
        Name = "Macedonia",
        Alpha2 = "MK",
        Alpha3 = "MKD",
        Coordinates = new[] {17, 8},
        CountryCode = "807",
        Iso31662 = "ISO 3166-2:MK",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Southern Europe",
        SubRegionCode = "039",
      },
      new GridTileMap
      {
        Name = "Madagascar",
        Alpha2 = "MG",
        Alpha3 = "MDG",
        Coordinates = new[] {19, 19},
        CountryCode = "450",
        Iso31662 = "ISO 3166-2:MG",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Eastern Africa",
        SubRegionCode = "014",
      },
      new GridTileMap
      {
        Name = "Malawi",
        Alpha2 = "MW",
        Alpha3 = "MWI",
        Coordinates = new[] {15, 17},
        CountryCode = "454",
        Iso31662 = "ISO 3166-2:MW",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Eastern Africa",
        SubRegionCode = "014",
      },
      new GridTileMap
      {
        Name = "Malaysia",
        Alpha2 = "MY",
        Alpha3 = "MYS",
        Coordinates = new[] {24, 11},
        CountryCode = "458",
        Iso31662 = "ISO 3166-2:MY",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "South-Eastern Asia",
        SubRegionCode = "035",
      },
      new GridTileMap
      {
        Name = "Maldives",
        Alpha2 = "MV",
        Alpha3 = "MDV",
        Coordinates = new[] {21, 12},
        CountryCode = "462",
        Iso31662 = "ISO 3166-2:MV",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Southern Asia",
        SubRegionCode = "034",
      },
      new GridTileMap
      {
        Name = "Mali",
        Alpha2 = "ML",
        Alpha3 = "MLI",
        Coordinates = new[] {14, 12},
        CountryCode = "466",
        Iso31662 = "ISO 3166-2:ML",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Western Africa",
        SubRegionCode = "011",
      },
      new GridTileMap
      {
        Name = "Malta",
        Alpha2 = "MT",
        Alpha3 = "MLT",
        Coordinates = new[] {11, 8},
        CountryCode = "470",
        Iso31662 = "ISO 3166-2:MT",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Southern Europe",
        SubRegionCode = "039",
      },
      new GridTileMap
      {
        Name = "Marshall Islands",
        Alpha2 = "MH",
        Alpha3 = "MHL",
        Coordinates = new[] {26, 15},
        CountryCode = "584",
        Iso31662 = "ISO 3166-2:MH",
        Region = "Oceania",
        RegionCode = "009",
        SubRegion = "Micronesia",
        SubRegionCode = "057",
      },
      new GridTileMap
      {
        Name = "Mauritania",
        Alpha2 = "MR",
        Alpha3 = "MRT",
        Coordinates = new[] {11, 12},
        CountryCode = "478",
        Iso31662 = "ISO 3166-2:MR",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Western Africa",
        SubRegionCode = "011",
      },
      new GridTileMap
      {
        Name = "Mauritius",
        Alpha2 = "MU",
        Alpha3 = "MUS",
        Coordinates = new[] {19, 20},
        CountryCode = "480",
        Iso31662 = "ISO 3166-2:MU",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Eastern Africa",
        SubRegionCode = "014",
      },
      new GridTileMap
      {
        Name = "Mexico",
        Alpha2 = "MX",
        Alpha3 = "MEX",
        Coordinates = new[] {1, 3},
        CountryCode = "484",
        Iso31662 = "ISO 3166-2:MX",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Central America",
        SubRegionCode = "013",
      },
      new GridTileMap
      {
        Name = "Micronesia (Federated States of)",
        Alpha2 = "FM",
        Alpha3 = "FSM",
        Coordinates = new[] {26, 16},
        CountryCode = "583",
        Iso31662 = "ISO 3166-2:FM",
        Region = "Oceania",
        RegionCode = "009",
        SubRegion = "Micronesia",
        SubRegionCode = "057",
      },
      new GridTileMap
      {
        Name = "Moldova (Republic of)",
        Alpha2 = "MD",
        Alpha3 = "MDA",
        Coordinates = new[] {18, 5},
        CountryCode = "498",
        Iso31662 = "ISO 3166-2:MD",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Eastern Europe",
        SubRegionCode = "151",
      },
      new GridTileMap
      {
        Name = "Mongolia",
        Alpha2 = "MN",
        Alpha3 = "MNG",
        Coordinates = new[] {25, 5},
        CountryCode = "496",
        Iso31662 = "ISO 3166-2:MN",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Eastern Asia",
        SubRegionCode = "030",
      },
      new GridTileMap
      {
        Name = "Montenegro",
        Alpha2 = "ME",
        Alpha3 = "MNE",
        Coordinates = new[] {15, 8},
        CountryCode = "499",
        Iso31662 = "ISO 3166-2:ME",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Southern Europe",
        SubRegionCode = "039",
      },
      new GridTileMap
      {
        Name = "Morocco",
        Alpha2 = "MA",
        Alpha3 = "MAR",
        Coordinates = new[] {12, 11},
        CountryCode = "504",
        Iso31662 = "ISO 3166-2:MA",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Northern Africa",
        SubRegionCode = "015",
      },
      new GridTileMap
      {
        Name = "Mozambique",
        Alpha2 = "MZ",
        Alpha3 = "MOZ",
        Coordinates = new[] {16, 17},
        CountryCode = "508",
        Iso31662 = "ISO 3166-2:MZ",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Eastern Africa",
        SubRegionCode = "014",
      },
      new GridTileMap
      {
        Name = "Myanmar",
        Alpha2 = "MM",
        Alpha3 = "MMR",
        Coordinates = new[] {24, 8},
        CountryCode = "104",
        Iso31662 = "ISO 3166-2:MM",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "South-Eastern Asia",
        SubRegionCode = "035",
      },
      new GridTileMap
      {
        Name = "Namibia",
        Alpha2 = "NA",
        Alpha3 = "NAM",
        Coordinates = new[] {15, 19},
        CountryCode = "516",
        Iso31662 = "ISO 3166-2:NA",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Southern Africa",
        SubRegionCode = "018",
      },
      new GridTileMap
      {
        Name = "Nauru",
        Alpha2 = "NR",
        Alpha3 = "NRU",
        Coordinates = new[] {26, 17},
        CountryCode = "520",
        Iso31662 = "ISO 3166-2:NR",
        Region = "Oceania",
        RegionCode = "009",
        SubRegion = "Micronesia",
        SubRegionCode = "057",
      },
      new GridTileMap
      {
        Name = "Nepal",
        Alpha2 = "NP",
        Alpha3 = "NPL",
        Coordinates = new[] {23, 9},
        CountryCode = "524",
        Iso31662 = "ISO 3166-2:NP",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Southern Asia",
        SubRegionCode = "034",
      },
      new GridTileMap
      {
        Name = "Netherlands",
        Alpha2 = "NL",
        Alpha3 = "NLD",
        Coordinates = new[] {13, 4},
        CountryCode = "528",
        Iso31662 = "ISO 3166-2:NL",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Western Europe",
        SubRegionCode = "155",
      },
      new GridTileMap
      {
        Name = "New Zealand",
        Alpha2 = "NZ",
        Alpha3 = "NZL",
        Coordinates = new[] {26, 21},
        CountryCode = "554",
        Iso31662 = "ISO 3166-2:NZ",
        Region = "Oceania",
        RegionCode = "009",
        SubRegion = "Australia and New Zealand",
        SubRegionCode = "053",
      },
      new GridTileMap
      {
        Name = "Nicaragua",
        Alpha2 = "NI",
        Alpha3 = "NIC",
        Coordinates = new[] {2, 6},
        CountryCode = "558",
        Iso31662 = "ISO 3166-2:NI",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Central America",
        SubRegionCode = "013",
      },
      new GridTileMap
      {
        Name = "Niger",
        Alpha2 = "NE",
        Alpha3 = "NER",
        Coordinates = new[] {15, 12},
        CountryCode = "562",
        Iso31662 = "ISO 3166-2:NE",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Western Africa",
        SubRegionCode = "011",
      },
      new GridTileMap
      {
        Name = "Nigeria",
        Alpha2 = "NG",
        Alpha3 = "NGA",
        Coordinates = new[] {13, 15},
        CountryCode = "566",
        Iso31662 = "ISO 3166-2:NG",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Western Africa",
        SubRegionCode = "011",
      },
      new GridTileMap
      {
        Name = "Norway",
        Alpha2 = "NO",
        Alpha3 = "NOR",
        Coordinates = new[] {15, 1},
        CountryCode = "578",
        Iso31662 = "ISO 3166-2:NO",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Northern Europe",
        SubRegionCode = "154",
      },
      new GridTileMap
      {
        Name = "Oman",
        Alpha2 = "OM",
        Alpha3 = "OMN",
        Coordinates = new[] {19, 11},
        CountryCode = "512",
        Iso31662 = "ISO 3166-2:OM",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Western Asia",
        SubRegionCode = "145",
      },
      new GridTileMap
      {
        Name = "Pakistan",
        Alpha2 = "PK",
        Alpha3 = "PAK",
        Coordinates = new[] {21, 8},
        CountryCode = "586",
        Iso31662 = "ISO 3166-2:PK",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Southern Asia",
        SubRegionCode = "034",
      },
      new GridTileMap
      {
        Name = "Palau",
        Alpha2 = "PW",
        Alpha3 = "PLW",
        Coordinates = new[] {25, 16},
        CountryCode = "585",
        Iso31662 = "ISO 3166-2:PW",
        Region = "Oceania",
        RegionCode = "009",
        SubRegion = "Micronesia",
        SubRegionCode = "057",
      },
      new GridTileMap
      {
        Name = "Panama",
        Alpha2 = "PA",
        Alpha3 = "PAN",
        Coordinates = new[] {4, 8},
        CountryCode = "591",
        Iso31662 = "ISO 3166-2:PA",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Central America",
        SubRegionCode = "013",
      },
      new GridTileMap
      {
        Name = "Papua New Guinea",
        Alpha2 = "PG",
        Alpha3 = "PNG",
        Coordinates = new[] {25, 17},
        CountryCode = "598",
        Iso31662 = "ISO 3166-2:PG",
        Region = "Oceania",
        RegionCode = "009",
        SubRegion = "Melanesia",
        SubRegionCode = "054",
      },
      new GridTileMap
      {
        Name = "Paraguay",
        Alpha2 = "PY",
        Alpha3 = "PRY",
        Coordinates = new[] {6, 12},
        CountryCode = "600",
        Iso31662 = "ISO 3166-2:PY",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "South America",
        SubRegionCode = "005",
      },
      new GridTileMap
      {
        Name = "Peru",
        Alpha2 = "PE",
        Alpha3 = "PER",
        Coordinates = new[] {5, 11},
        CountryCode = "604",
        Iso31662 = "ISO 3166-2:PE",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "South America",
        SubRegionCode = "005",
      },
      new GridTileMap
      {
        Name = "Philippines",
        Alpha2 = "PH",
        Alpha3 = "PHL",
        Coordinates = new[] {26, 11},
        CountryCode = "608",
        Iso31662 = "ISO 3166-2:PH",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "South-Eastern Asia",
        SubRegionCode = "035",
      },
      new GridTileMap
      {
        Name = "Poland",
        Alpha2 = "PL",
        Alpha3 = "POL",
        Coordinates = new[] {15, 4},
        CountryCode = "616",
        Iso31662 = "ISO 3166-2:PL",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Eastern Europe",
        SubRegionCode = "151",
      },
      new GridTileMap
      {
        Name = "Portugal",
        Alpha2 = "PT",
        Alpha3 = "PRT",
        Coordinates = new[] {11, 6},
        CountryCode = "620",
        Iso31662 = "ISO 3166-2:PT",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Southern Europe",
        SubRegionCode = "039",
      },
      new GridTileMap
      {
        Name = "Qatar",
        Alpha2 = "QA",
        Alpha3 = "QAT",
        Coordinates = new[] {19, 10},
        CountryCode = "634",
        Iso31662 = "ISO 3166-2:QA",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Western Asia",
        SubRegionCode = "145",
      },
      new GridTileMap
      {
        Name = "Romania",
        Alpha2 = "RO",
        Alpha3 = "ROU",
        Coordinates = new[] {17, 6},
        CountryCode = "642",
        Iso31662 = "ISO 3166-2:RO",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Eastern Europe",
        SubRegionCode = "151",
      },
      new GridTileMap
      {
        Name = "Russian Federation",
        Alpha2 = "RU",
        Alpha3 = "RUS",
        Coordinates = new[] {25, 4},
        CountryCode = "643",
        Iso31662 = "ISO 3166-2:RU",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Eastern Europe",
        SubRegionCode = "151",
      },
      new GridTileMap
      {
        Name = "Rwanda",
        Alpha2 = "RW",
        Alpha3 = "RWA",
        Coordinates = new[] {16, 16},
        CountryCode = "646",
        Iso31662 = "ISO 3166-2:RW",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Eastern Africa",
        SubRegionCode = "014",
      },
      new GridTileMap
      {
        Name = "St. Kitts & Nevis",
        Alpha2 = "KN",
        Alpha3 = "KNA",
        Coordinates = new[] {6, 5},
        CountryCode = "659",
        Iso31662 = "ISO 3166-2:KN",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Caribbean",
        SubRegionCode = "029",
      },
      new GridTileMap
      {
        Name = "St. Lucia",
        Alpha2 = "LC",
        Alpha3 = "LCA",
        Coordinates = new[] {7, 5},
        CountryCode = "662",
        Iso31662 = "ISO 3166-2:LC",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Caribbean",
        SubRegionCode = "029",
      },
      new GridTileMap
      {
        Name = "St. Vincent & the Grenadines",
        Alpha2 = "VC",
        Alpha3 = "VCT",
        Coordinates = new[] {7, 6},
        CountryCode = "670",
        Iso31662 = "ISO 3166-2:VC",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Caribbean",
        SubRegionCode = "029",
      },
      new GridTileMap
      {
        Name = "Samoa",
        Alpha2 = "WS",
        Alpha3 = "WSM",
        Coordinates = new[] {28, 18},
        CountryCode = "882",
        Iso31662 = "ISO 3166-2:WS",
        Region = "Oceania",
        RegionCode = "009",
        SubRegion = "Polynesia",
        SubRegionCode = "061",
      },
      new GridTileMap
      {
        Name = "Sao Tome and Principe",
        Alpha2 = "ST",
        Alpha3 = "STP",
        Coordinates = new[] {11, 16},
        CountryCode = "678",
        Iso31662 = "ISO 3166-2:ST",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Middle Africa",
        SubRegionCode = "017",
      },
      new GridTileMap
      {
        Name = "Saudi Arabia",
        Alpha2 = "SA",
        Alpha3 = "SAU",
        Coordinates = new[] {19, 9},
        CountryCode = "682",
        Iso31662 = "ISO 3166-2:SA",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Western Asia",
        SubRegionCode = "145",
      },
      new GridTileMap
      {
        Name = "Senegal",
        Alpha2 = "SN",
        Alpha3 = "SEN",
        Coordinates = new[] {13, 12},
        CountryCode = "686",
        Iso31662 = "ISO 3166-2:SN",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Western Africa",
        SubRegionCode = "011",
      },
      new GridTileMap
      {
        Name = "Serbia",
        Alpha2 = "RS",
        Alpha3 = "SRB",
        Coordinates = new[] {16, 7},
        CountryCode = "688",
        Iso31662 = "ISO 3166-2:RS",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Southern Europe",
        SubRegionCode = "039",
      },
      new GridTileMap
      {
        Name = "Seychelles",
        Alpha2 = "SC",
        Alpha3 = "SYC",
        Coordinates = new[] {18, 17},
        CountryCode = "690",
        Iso31662 = "ISO 3166-2:SC",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Eastern Africa",
        SubRegionCode = "014",
      },
      new GridTileMap
      {
        Name = "Sierra Leone",
        Alpha2 = "SL",
        Alpha3 = "SLE",
        Coordinates = new[] {12, 13},
        CountryCode = "694",
        Iso31662 = "ISO 3166-2:SL",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Western Africa",
        SubRegionCode = "011",
      },
      new GridTileMap
      {
        Name = "Singapore",
        Alpha2 = "SG",
        Alpha3 = "SGP",
        Coordinates = new[] {24, 13},
        CountryCode = "702",
        Iso31662 = "ISO 3166-2:SG",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "South-Eastern Asia",
        SubRegionCode = "035",
      },
      new GridTileMap
      {
        Name = "Slovakia",
        Alpha2 = "SK",
        Alpha3 = "SVK",
        Coordinates = new[] {16, 5},
        CountryCode = "703",
        Iso31662 = "ISO 3166-2:SK",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Eastern Europe",
        SubRegionCode = "151",
      },
      new GridTileMap
      {
        Name = "Slovenia",
        Alpha2 = "SI",
        Alpha3 = "SVN",
        Coordinates = new[] {14, 6},
        CountryCode = "705",
        Iso31662 = "ISO 3166-2:SI",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Southern Europe",
        SubRegionCode = "039",
      },
      new GridTileMap
      {
        Name = "Solomon Islands",
        Alpha2 = "SB",
        Alpha3 = "SLB",
        Coordinates = new[] {26, 18},
        CountryCode = "090",
        Iso31662 = "ISO 3166-2:SB",
        Region = "Oceania",
        RegionCode = "009",
        SubRegion = "Melanesia",
        SubRegionCode = "054",
      },
      new GridTileMap
      {
        Name = "Somalia",
        Alpha2 = "SO",
        Alpha3 = "SOM",
        Coordinates = new[] {18, 14},
        CountryCode = "706",
        Iso31662 = "ISO 3166-2:SO",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Eastern Africa",
        SubRegionCode = "014",
      },
      new GridTileMap
      {
        Name = "South Africa",
        Alpha2 = "ZA",
        Alpha3 = "ZAF",
        Coordinates = new[] {16, 20},
        CountryCode = "710",
        Iso31662 = "ISO 3166-2:ZA",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Southern Africa",
        SubRegionCode = "018",
      },
      new GridTileMap
      {
        Name = "South Sudan",
        Alpha2 = "SS",
        Alpha3 = "SSD",
        Coordinates = new[] {15, 13},
        CountryCode = "728",
        Iso31662 = "ISO 3166-2:SS",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Eastern Africa",
        SubRegionCode = "014",
      },
      new GridTileMap
      {
        Name = "Spain",
        Alpha2 = "ES",
        Alpha3 = "ESP",
        Coordinates = new[] {12, 6},
        CountryCode = "724",
        Iso31662 = "ISO 3166-2:ES",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Southern Europe",
        SubRegionCode = "039",
      },
      new GridTileMap
      {
        Name = "Sri Lanka",
        Alpha2 = "LK",
        Alpha3 = "LKA",
        Coordinates = new[] {22, 11},
        CountryCode = "144",
        Iso31662 = "ISO 3166-2:LK",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Southern Asia",
        SubRegionCode = "034",
      },
      new GridTileMap
      {
        Name = "Sudan",
        Alpha2 = "SD",
        Alpha3 = "SDN",
        Coordinates = new[] {16, 12},
        CountryCode = "729",
        Iso31662 = "ISO 3166-2:SD",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Northern Africa",
        SubRegionCode = "015",
      },
      new GridTileMap
      {
        Name = "Suriname",
        Alpha2 = "SR",
        Alpha3 = "SUR",
        Coordinates = new[] {7, 11},
        CountryCode = "740",
        Iso31662 = "ISO 3166-2:SR",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "South America",
        SubRegionCode = "005",
      },
      new GridTileMap
      {
        Name = "Swaziland",
        Alpha2 = "SZ",
        Alpha3 = "SWZ",
        Coordinates = new[] {16, 19},
        CountryCode = "748",
        Iso31662 = "ISO 3166-2:SZ",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Southern Africa",
        SubRegionCode = "018",
      },
      new GridTileMap
      {
        Name = "Sweden",
        Alpha2 = "SE",
        Alpha3 = "SWE",
        Coordinates = new[] {16, 1},
        CountryCode = "752",
        Iso31662 = "ISO 3166-2:SE",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Northern Europe",
        SubRegionCode = "154",
      },
      new GridTileMap
      {
        Name = "Switzerland",
        Alpha2 = "CH",
        Alpha3 = "CHE",
        Coordinates = new[] {14, 5},
        CountryCode = "756",
        Iso31662 = "ISO 3166-2:CH",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Western Europe",
        SubRegionCode = "155",
      },
      new GridTileMap
      {
        Name = "Syria",
        Alpha2 = "SY",
        Alpha3 = "SYR",
        Coordinates = new[] {19, 7},
        CountryCode = "760",
        Iso31662 = "ISO 3166-2:SY",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Western Asia",
        SubRegionCode = "145",
      },
      new GridTileMap
      {
        Name = "Tajikistan",
        Alpha2 = "TJ",
        Alpha3 = "TJK",
        Coordinates = new[] {23, 7},
        CountryCode = "762",
        Iso31662 = "ISO 3166-2:TJ",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Central Asia",
        SubRegionCode = "143",
      },
      new GridTileMap
      {
        Name = "Tanzania",
        Alpha2 = "TZ",
        Alpha3 = "TZA",
        Coordinates = new[] {17, 16},
        CountryCode = "834",
        Iso31662 = "ISO 3166-2:TZ",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Eastern Africa",
        SubRegionCode = "014",
      },
      new GridTileMap
      {
        Name = "Thailand",
        Alpha2 = "TH",
        Alpha3 = "THA",
        Coordinates = new[] {24, 10},
        CountryCode = "764",
        Iso31662 = "ISO 3166-2:TH",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "South-Eastern Asia",
        SubRegionCode = "035",
      },
      new GridTileMap
      {
        Name = "Timor-Leste",
        Alpha2 = "TL",
        Alpha3 = "TLS",
        Coordinates = new[] {25, 14},
        CountryCode = "626",
        Iso31662 = "ISO 3166-2:TL",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "South-Eastern Asia",
        SubRegionCode = "035",
      },
      new GridTileMap
      {
        Name = "Togo",
        Alpha2 = "TG",
        Alpha3 = "TGO",
        Coordinates = new[] {14, 14},
        CountryCode = "768",
        Iso31662 = "ISO 3166-2:TG",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Western Africa",
        SubRegionCode = "011",
      },
      new GridTileMap
      {
        Name = "Tonga",
        Alpha2 = "TO",
        Alpha3 = "TON",
        Coordinates = new[] {28, 19},
        CountryCode = "776",
        Iso31662 = "ISO 3166-2:TO",
        Region = "Oceania",
        RegionCode = "009",
        SubRegion = "Polynesia",
        SubRegionCode = "061",
      },
      new GridTileMap
      {
        Name = "Trinidad & Tobago",
        Alpha2 = "TT",
        Alpha3 = "TTO",
        Coordinates = new[] {7, 9},
        CountryCode = "780",
        Iso31662 = "ISO 3166-2:TT",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Caribbean",
        SubRegionCode = "029",
      },
      new GridTileMap
      {
        Name = "Tunisia",
        Alpha2 = "TN",
        Alpha3 = "TUN",
        Coordinates = new[] {14, 11},
        CountryCode = "788",
        Iso31662 = "ISO 3166-2:TN",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Northern Africa",
        SubRegionCode = "015",
      },
      new GridTileMap
      {
        Name = "Turkey",
        Alpha2 = "TR",
        Alpha3 = "TUR",
        Coordinates = new[] {18, 7},
        CountryCode = "792",
        Iso31662 = "ISO 3166-2:TR",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Western Asia",
        SubRegionCode = "145",
      },
      new GridTileMap
      {
        Name = "Turkmenistan",
        Alpha2 = "TM",
        Alpha3 = "TKM",
        Coordinates = new[] {22, 7},
        CountryCode = "795",
        Iso31662 = "ISO 3166-2:TM",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Central Asia",
        SubRegionCode = "143",
      },
      new GridTileMap
      {
        Name = "Tuvalu",
        Alpha2 = "TV",
        Alpha3 = "TUV",
        Coordinates = new[] {27, 18},
        CountryCode = "798",
        Iso31662 = "ISO 3166-2:TV",
        Region = "Oceania",
        RegionCode = "009",
        SubRegion = "Polynesia",
        SubRegionCode = "061",
      },
      new GridTileMap
      {
        Name = "Uganda",
        Alpha2 = "UG",
        Alpha3 = "UGA",
        Coordinates = new[] {16, 15},
        CountryCode = "800",
        Iso31662 = "ISO 3166-2:UG",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Eastern Africa",
        SubRegionCode = "014",
      },
      new GridTileMap
      {
        Name = "Ukraine",
        Alpha2 = "UA",
        Alpha3 = "UKR",
        Coordinates = new[] {17, 5},
        CountryCode = "804",
        Iso31662 = "ISO 3166-2:UA",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Eastern Europe",
        SubRegionCode = "151",
      },
      new GridTileMap
      {
        Name = "United Arab Emirates",
        Alpha2 = "AE",
        Alpha3 = "ARE",
        Coordinates = new[] {20, 10},
        CountryCode = "784",
        Iso31662 = "ISO 3166-2:AE",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Western Asia",
        SubRegionCode = "145",
      },
      new GridTileMap
      {
        Name = "Great Britain and Northern Ireland",
        Alpha2 = "GB",
        Alpha3 = "GBR",
        Coordinates = new[] {11, 4},
        CountryCode = "826",
        Iso31662 = "ISO 3166-2:GB",
        Region = "Europe",
        RegionCode = "150",
        SubRegion = "Northern Europe",
        SubRegionCode = "154",
      },
      new GridTileMap
      {
        Name = "United States of America",
        Alpha2 = "US",
        Alpha3 = "USA",
        Coordinates = new[] {1, 2},
        CountryCode = "840",
        Iso31662 = "ISO 3166-2:US",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "Northern America",
        SubRegionCode = "021",
      },
      new GridTileMap
      {
        Name = "Uruguay",
        Alpha2 = "UY",
        Alpha3 = "URY",
        Coordinates = new[] {7, 12},
        CountryCode = "858",
        Iso31662 = "ISO 3166-2:UY",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "South America",
        SubRegionCode = "005",
      },
      new GridTileMap
      {
        Name = "Uzbekistan",
        Alpha2 = "UZ",
        Alpha3 = "UZB",
        Coordinates = new[] {22, 6},
        CountryCode = "860",
        Iso31662 = "ISO 3166-2:UZ",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Central Asia",
        SubRegionCode = "143",
      },
      new GridTileMap
      {
        Name = "Vanuatu",
        Alpha2 = "VU",
        Alpha3 = "VUT",
        Coordinates = new[] {26, 19},
        CountryCode = "548",
        Iso31662 = "ISO 3166-2:VU",
        Region = "Oceania",
        RegionCode = "009",
        SubRegion = "Melanesia",
        SubRegionCode = "054",
      },
      new GridTileMap
      {
        Name = "Venezuela",
        Alpha2 = "VE",
        Alpha3 = "VEN",
        Coordinates = new[] {6, 9},
        CountryCode = "862",
        Iso31662 = "ISO 3166-2:VE",
        Region = "Americas",
        RegionCode = "019",
        SubRegion = "South America",
        SubRegionCode = "005",
      },
      new GridTileMap
      {
        Name = "Viet Nam",
        Alpha2 = "VN",
        Alpha3 = "VNM",
        Coordinates = new[] {26, 9},
        CountryCode = "704",
        Iso31662 = "ISO 3166-2:VN",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "South-Eastern Asia",
        SubRegionCode = "035",
      },
      new GridTileMap
      {
        Name = "Yemen",
        Alpha2 = "YE",
        Alpha3 = "YEM",
        Coordinates = new[] {18, 11},
        CountryCode = "887",
        Iso31662 = "ISO 3166-2:YE",
        Region = "Asia",
        RegionCode = "142",
        SubRegion = "Western Asia",
        SubRegionCode = "145",
      },
      new GridTileMap
      {
        Name = "Zambia",
        Alpha2 = "ZM",
        Alpha3 = "ZMB",
        Coordinates = new[] {14, 18},
        CountryCode = "894",
        Iso31662 = "ISO 3166-2:ZM",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Eastern Africa",
        SubRegionCode = "014",
      },
      new GridTileMap
      {
        Name = "Zimbabwe",
        Alpha2 = "ZW",
        Alpha3 = "ZWE",
        Coordinates = new[] {16, 18},
        CountryCode = "716",
        Iso31662 = "ISO 3166-2:ZW",
        Region = "Africa",
        RegionCode = "002",
        SubRegion = "Eastern Africa",
        SubRegionCode = "014",
      },
    };
  }
}
